### NumPy Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
list1 = [1,2,3,4,5] # difference between nparray and list is that nparray have no commas & it can be n-dimentional
nparray = np.array(list1)
print(nparray)

[1 2 3 4 5]


In [3]:
list2 = [[1,2,3],[4,5,6]]
nparray2 = np.array(list2)
print(nparray2)

[[1 2 3]
 [4 5 6]]


In [4]:
print(nparray2 - 1) # we call simply perform all function on nparray

print('--------')

toyprise = [ 12,13,14,15]
# print(toyprise - 2) --> will cause an error becasue we cannt do operations directly on list
# so for that we will do following steps which will be taken taken

for i in range(len(toyprise)) :
    toyprise[i] -= 2
    
print(toyprise)

[[0 1 2]
 [3 4 5]]
--------
[10, 11, 12, 13]


In [5]:
np.cumsum(list1) # comulative sum

array([ 1,  3,  6, 10, 15], dtype=int32)

In [6]:
list3 = [-1.2, +0.3, -1.6, +2.8, +4.5, -6.7] # making all postive
np.abs(list3)

array([1.2, 0.3, 1.6, 2.8, 4.5, 6.7])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
print(np.amax(list1))
print(np.amin(list1))

5
1


In [10]:
np.around(list3) # round off according to significant number

array([-1.,  0., -2.,  3.,  4., -7.])

# Pandas Series

In [11]:
# Create a Series using a NumPy array of ages with the default numerical indices
ages = np.array([11, 12, 13, 14, 15])
series1 = pd.Series(ages)
print(series1)

0    11
1    12
2    13
3    14
4    15
dtype: int32


In [12]:
ages = np.array([21, 23, 5, 14])
Series2 = pd.Series(ages, index = ['Qasim', 'Iqra', 'Qalb -e- Sakoon', 'Begum'])
Series2

Qasim              21
Iqra               23
Qalb -e- Sakoon     5
Begum              14
dtype: int32

In [13]:
ages = np.array([11, 12, 13, 14, 15]) #without series it is just a np-array
print(ages)

[11 12 13 14 15]


In [14]:
print(series1)
print(pd.Series(series1).dtype)
print(pd.Series(series1).shape)
print(pd.Series(series1).ndim)
print(pd.Series(series1).nbytes)
print(pd.Series(series1).size)
print(pd.Series(series1).idxmax)
print('\n')
print(pd.Series(series1).transpose)

0    11
1    12
2    13
3    14
4    15
dtype: int32
int32
(5,)
1
20
5
<bound method Series.idxmax of 0    11
1    12
2    13
3    14
4    15
dtype: int32>


<bound method IndexOpsMixin.transpose of 0    11
1    12
2    13
3    14
4    15
dtype: int32>


In [15]:
arr = pd.Series(series1).array
print(arr)

<PandasArray>
[11, 12, 13, 14, 15]
Length: 5, dtype: int32


In [16]:
ser = pd.Series(pd.Categorical(['a', 'b', 'a', 'c', 'd']))
print(ser)

0    a
1    b
2    a
3    c
4    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']


In [17]:
ser.array

['a', 'b', 'a', 'c', 'd']
Categories (4, object): ['a', 'b', 'c', 'd']

In [18]:
pd.Series([11,12,13,14]).values

array([11, 12, 13, 14], dtype=int64)

In [19]:
list('aabcad')

['a', 'a', 'b', 'c', 'a', 'd']

In [20]:
pd.Series(list('aabdesf')).values

array(['a', 'a', 'b', 'd', 'e', 's', 'f'], dtype=object)

In [21]:
pd.Series(list('aabc')).astype('category').values

['a', 'a', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']

In [22]:
len(pytz.all_timezones) # pytz LIbrary about times

pytz.all_timezones[::20]

['Africa/Abidjan',
 'Africa/Douala',
 'Africa/Mbabane',
 'America/Argentina/Catamarca',
 'America/Belize',
 'America/Curacao',
 'America/Guatemala',
 'America/Kentucky/Louisville',
 'America/Mexico_City',
 'America/Phoenix',
 'America/Shiprock',
 'America/Yellowknife',
 'Asia/Ashgabat',
 'Asia/Dili',
 'Asia/Katmandu',
 'Asia/Pyongyang',
 'Asia/Tokyo',
 'Atlantic/Madeira',
 'Australia/Perth',
 'Canada/Saskatchewan',
 'Etc/GMT+6',
 'Etc/Greenwich',
 'Europe/Gibraltar',
 'Europe/Oslo',
 'Europe/Vatican',
 'Indian/Christmas',
 'Mexico/General',
 'Pacific/Guam',
 'Pacific/Saipan',
 'US/East-Indiana']

In [23]:
pytz.country_timezones('US')

['America/New_York',
 'America/Detroit',
 'America/Kentucky/Louisville',
 'America/Kentucky/Monticello',
 'America/Indiana/Indianapolis',
 'America/Indiana/Vincennes',
 'America/Indiana/Winamac',
 'America/Indiana/Marengo',
 'America/Indiana/Petersburg',
 'America/Indiana/Vevay',
 'America/Chicago',
 'America/Indiana/Tell_City',
 'America/Indiana/Knox',
 'America/Menominee',
 'America/North_Dakota/Center',
 'America/North_Dakota/New_Salem',
 'America/North_Dakota/Beulah',
 'America/Denver',
 'America/Boise',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Anchorage',
 'America/Juneau',
 'America/Sitka',
 'America/Metlakatla',
 'America/Yakutat',
 'America/Nome',
 'America/Adak',
 'Pacific/Honolulu']

In [24]:
list(filter(lambda x: 'UTC' in x, pytz.all_timezones))

['Etc/UTC', 'UTC']

In [25]:
pd.Series(pd.date_range('20201205', periods=5,tz='America/Nome')).values

array(['2020-12-05T09:00:00.000000000', '2020-12-06T09:00:00.000000000',
       '2020-12-07T09:00:00.000000000', '2020-12-08T09:00:00.000000000',
       '2020-12-09T09:00:00.000000000'], dtype='datetime64[ns]')

# Pandas Data Frame

In [3]:
dataf = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
    ],
    columns=['name','address','age'])
dataf

name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51

In [4]:
dataf.set_index('name')

address  age
name                          
John Smith    123 Main St   34
Jane Doe    456 Maple Ave   28
Joe Schmo    789 Broadway   51

In [8]:
Employees = pd.DataFrame([
    ['Qasim', 'Karsaz', 21],
    ['Asad', 'Poona', 23],
    ['Afaq', 'dalmiya', 24]
    ],
    columns = ['name', 'Address', 'age']
)

print(Employees)

    name  Address  age
0  Qasim   Karsaz   21
1   Asad    Poona   23
2   Afaq  dalmiya   24


In [9]:
Employees.set_index('name')

Address  age
name               
Qasim   Karsaz   21
Asad     Poona   23
Afaq   dalmiya   24

##  Creating, Loading, and Selecting Data with Pandas
Learn the basics of creating, loading, and selecting data in Pandas using DataFrames.

### Installation of pandas

In [30]:
import pandas as pd

### Create a DataFrame I
You can also add data using dictionaries.

In [2]:
df1 = pd.DataFrame({
  'Product ID': [1, 2, 3, 4],
  # add Product Name and Color here
  'Product Name': ['t-shirt', 't-shirt', 'skirt', 'skirt'],
  'Color': ['blue', 'green', 'red', 'black'] 
})

In [3]:
df1

Product ID Product Name  Color
0           1      t-shirt   blue
1           2      t-shirt  green
2           3        skirt    red
3           4        skirt  black

In [13]:
df1.set_index('Product ID') 

Product Name  Color
Product ID                    
1               t-shirt   blue
2               t-shirt  green
3                 skirt    red
4                 skirt  black

In [33]:
df2 = pd.DataFrame({
    'name': ['John Smith', 'Jane Doe', 'Joe Schmo'],
    'address': ['123 Main St.', '456 Maple Ave.', '789 Broadway'],
    'age': [34, 28, 51]
})

In [34]:
df2

name         address  age
0  John Smith    123 Main St.   34
1    Jane Doe  456 Maple Ave.   28
2   Joe Schmo    789 Broadway   51

### Create a DataFrame II
You can also add data using lists.

In [35]:
df2 = pd.DataFrame([
    ['John Smith', '123 Main St.', 34],
    ['Jane Doe', '456 Maple Ave.', 28],
    ['Joe Schmo', '789 Broadway', 51]
    ],
    columns=['name', 'address', 'age'])

In [36]:
df2

name         address  age
0  John Smith    123 Main St.   34
1    Jane Doe  456 Maple Ave.   28
2   Joe Schmo    789 Broadway   51

### Create a DataFrame III
you can also make data through csv (comma seperated files)

In [4]:
pd.read_csv('cupcakes.csv')

name cake_flavor frosting_flavor             topping
0  Chocolate Cake   chocolate       chocolate  chocolate shavings
1   Birthday Cake     vanilla         vanilla   rainbow sprinkles
2     Carrot Cake      carrot           cream              cheese

In [5]:
df = pd.read_csv('imdb.csv')

### Basic three steps head(), info(), describe()

In [39]:
df.head()

id                                       name   genre  year  imdb_rating
0   1                                     Avatar  action  2009          7.9
1   2                             Jurassic World  action  2015          7.3
2   3                               The Avengers  action  2012          8.1
3   4                            The Dark Knight  action  2008          9.0
4   5  Star Wars: Episode I - The Phantom Menace  action  1999          6.6

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           220 non-null    int64  
 1   name         220 non-null    object 
 2   genre        220 non-null    object 
 3   year         220 non-null    int64  
 4   imdb_rating  220 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 8.7+ KB


In [41]:
df.describe()

id         year  imdb_rating
count  220.000000   220.000000   220.000000
mean   110.500000  2002.963636     6.993636
std     63.652704    11.132598     0.969750
min      1.000000  1937.000000     4.200000
25%     55.750000  1999.000000     6.400000
50%    110.500000  2005.500000     7.100000
75%    165.250000  2011.000000     7.700000
max    220.000000  2015.000000     9.000000

### Column Selection 

In [42]:
single_column = df['name']

single_column

0                                         Avatar
1                                 Jurassic World
2                                   The Avengers
3                                The Dark Knight
4      Star Wars: Episode I - The Phantom Menace
                         ...                    
215                                     Hannibal
216                          Catch Me If You Can
217                                    Big Daddy
218                                        Se7en
219                                        Seven
Name: name, Length: 220, dtype: object

In [43]:
another_way = df.name

another_way

0                                         Avatar
1                                 Jurassic World
2                                   The Avengers
3                                The Dark Knight
4      Star Wars: Episode I - The Phantom Menace
                         ...                    
215                                     Hannibal
216                          Catch Me If You Can
217                                    Big Daddy
218                                        Se7en
219                                        Seven
Name: name, Length: 220, dtype: object

In [44]:
print(type(df.name))

<class 'pandas.core.series.Series'>


In [45]:
print(type(df['name']))

<class 'pandas.core.series.Series'>


In [46]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [47]:
multiple_column = df[['name', 'year']]

multiple_column

name  year
0                                       Avatar  2009
1                               Jurassic World  2015
2                                 The Avengers  2012
3                              The Dark Knight  2008
4    Star Wars: Episode I - The Phantom Menace  1999
..                                         ...   ...
215                                   Hannibal  2001
216                        Catch Me If You Can  2002
217                                  Big Daddy  1999
218                                      Se7en  1995
219                                      Seven  1979

[220 rows x 2 columns]

In [48]:
print(type(multiple_column))

<class 'pandas.core.frame.DataFrame'>


### Rows Selection

In [69]:
df.loc[[1,213,219]]

id            name   genre  year  imdb_rating
1      2  Jurassic World  action  2015          7.3
213  214       Gone Girl   drama  2014          8.2
219  220           Seven   drama  1979          6.1

In [49]:
df.iloc[0] 

id                  1
name           Avatar
genre          action
year             2009
imdb_rating       7.9
Name: 0, dtype: object

In [50]:
df.iloc[0:3]

id            name   genre  year  imdb_rating
0   1          Avatar  action  2009          7.9
1   2  Jurassic World  action  2015          7.3
2   3    The Avengers  action  2012          8.1

In [8]:
df.iloc[-7:-3]

id                 name  genre  year  imdb_rating
213  214            Gone Girl  drama  2014          8.2
214  215      Kung Fu Panda 2  drama  2011          7.3
215  216             Hannibal  drama  2001          6.7
216  217  Catch Me If You Can  drama  2002          8.0

In [9]:
df.iloc[-3:]

id       name  genre  year  imdb_rating
217  218  Big Daddy  drama  1999          6.4
218  219      Se7en  drama  1995          8.6
219  220      Seven  drama  1979          6.1

### Rows Selection with locgic operators

In [15]:
df.query('imdb_rating == 9.0')

id             name   genre  year  imdb_rating
3   4  The Dark Knight  action  2008          9.0

In [20]:
df.query('name == Se7en')

UndefinedVariableError: name 'Se7en' is not defined

In [18]:
df[df.name == 'Se7en']

id   name  genre  year  imdb_rating
218  219  Se7en  drama  1995          8.6

In [53]:
df[df.name == 'Gone Girl']

id       name  genre  year  imdb_rating
213  214  Gone Girl  drama  2014          8.2

In [54]:
df[df.name == 'Avatar']

id    name   genre  year  imdb_rating
0   1  Avatar  action  2009          7.9

In [55]:
df[(df.name == 'Avatar') | (df.name == 'Gone Girl')]  #using OR operator

id       name   genre  year  imdb_rating
0      1     Avatar  action  2009          7.9
213  214  Gone Girl   drama  2014          8.2

In [56]:
df.iloc[-2:]

id   name  genre  year  imdb_rating
218  219  Se7en  drama  1995          8.6
219  220  Seven  drama  1979          6.1

In [57]:
df[(df.name == 'Seven') & (df.imdb_rating == 6.1) ] # using AND operator

id   name  genre  year  imdb_rating
219  220  Seven  drama  1979          6.1

In [58]:
df[df.name.isin(['Avata', 'Gone Girl', 'Seven'])] # Avato is missing in the table "Avatar" is in the list

id       name  genre  year  imdb_rating
213  214  Gone Girl  drama  2014          8.2
219  220      Seven  drama  1979          6.1

In [59]:
df[df.name.isin(['Avatar', 'Gone Girl', 'Seven'])]

id       name   genre  year  imdb_rating
0      1     Avatar  action  2009          7.9
213  214  Gone Girl   drama  2014          8.2
219  220      Seven   drama  1979          6.1

In [62]:
df.loc[[1,213,219]]

id            name   genre  year  imdb_rating
1      2  Jurassic World  action  2015          7.3
213  214       Gone Girl   drama  2014          8.2
219  220           Seven   drama  1979          6.1

In [63]:
df2 = df.iloc[[1,213,219]]

id            name   genre  year  imdb_rating
1      2  Jurassic World  action  2015          7.3
213  214       Gone Girl   drama  2014          8.2
219  220           Seven   drama  1979          6.1

In [66]:
df3 = df2.reset_index()
df3

index        name         address  age
0      0  John Smith    123 Main St.   34
1      1    Jane Doe  456 Maple Ave.   28
2      2   Joe Schmo    789 Broadway   51

In [68]:
df2.reset_index(inplace = True , drop = True)
df2

name         address  age
0  John Smith    123 Main St.   34
1    Jane Doe  456 Maple Ave.   28
2   Joe Schmo    789 Broadway   51

# Hand made clinic data set

In [17]:
df = pd.DataFrame([
  ['January', 100, 100, 23, 100],
  ['February', 51, 45, 145, 45],
  ['March', 81, 96, 65, 96],
  ['April', 80, 80, 54, 180],
  ['May', 51, 54, 54, 154],
  ['June', 112, 109, 79, 129]],
  columns=['month', 'clinic_east',
           'clinic_north', 'clinic_south',
           'clinic_west'])
df

month  clinic_east  clinic_north  clinic_south  clinic_west
0   January          100           100            23          100
1  February           51            45           145           45
2     March           81            96            65           96
3     April           80            80            54          180
4       May           51            54            54          154
5      June          112           109            79          129

In [21]:
df['Time'] = [ '3:00', '4:00', '5:00', '6:00', '7:00', '8:00']

In [22]:
df

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
0   January          100           100            23          100  3:00
1  February           51            45           145           45  4:00
2     March           81            96            65           96  5:00
3     April           80            80            54          180  6:00
4       May           51            54            54          154  7:00
5      June          112           109            79          129  8:00

In [27]:
df.head(2)

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
0   January          100           100            23          100  3:00
1  February           51            45           145           45  4:00

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   month         6 non-null      object
 1   clinic_east   6 non-null      int64 
 2   clinic_north  6 non-null      int64 
 3   clinic_south  6 non-null      int64 
 4   clinic_west   6 non-null      int64 
 5   Time          6 non-null      object
dtypes: int64(4), object(2)
memory usage: 416.0+ bytes


In [31]:
df.describe()

clinic_east  clinic_north  clinic_south  clinic_west
count     6.000000      6.000000      6.000000     6.000000
mean     79.166667     80.666667     70.000000   117.333333
std      24.911176     26.058908     41.114474    47.739571
min      51.000000     45.000000     23.000000    45.000000
25%      58.250000     60.500000     54.000000    97.000000
50%      80.500000     88.000000     59.500000   114.500000
75%      95.250000     99.000000     75.500000   147.750000
max     112.000000    109.000000    145.000000   180.000000

In [37]:
clinic_north = df.clinic_north
print(clinic_north)
print()
print(type(clinic_north))

0    100
1     45
2     96
3     80
4     54
5    109
Name: clinic_north, dtype: int64

<class 'pandas.core.series.Series'>


In [38]:
another_way = df['clinic_north']
print(another_way)

0    100
1     45
2     96
3     80
4     54
5    109
Name: clinic_north, dtype: int64


In [40]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [44]:
clinic_north_south = df[['clinic_north', 'clinic_south']]
clinic_north_south

clinic_north  clinic_south
0           100            23
1            45           145
2            96            65
3            80            54
4            54            54
5           109            79

In [49]:
print(type(clinic_north_south))


<class 'pandas.core.frame.DataFrame'>


In [50]:
df.iloc[0]

month           January
clinic_east         100
clinic_north        100
clinic_south         23
clinic_west         100
Time               3:00
Name: 0, dtype: object

In [51]:
df.iloc[[1,2]]

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
1  February           51            45           145           45  4:00
2     March           81            96            65           96  5:00

In [48]:
df.iloc[0:2]

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
0   January          100           100            23          100  3:00
1  February           51            45           145           45  4:00

In [53]:
df.loc[2]

month           March
clinic_east        81
clinic_north       96
clinic_south       65
clinic_west        96
Time             5:00
Name: 2, dtype: object

In [54]:
df.loc[[2,3,4]]

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
2  March           81            96            65           96  5:00
3  April           80            80            54          180  6:00
4    May           51            54            54          154  7:00

In [63]:
df.loc[3:5]

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
3  April           80            80            54          180  6:00
4    May           51            54            54          154  7:00
5   June          112           109            79          129  8:00

In [67]:
df.loc[-3]

KeyError: -3

In [68]:
df.iloc[-3]

month           April
clinic_east        80
clinic_north       80
clinic_south       54
clinic_west       180
Time             6:00
Name: 3, dtype: object

In [62]:
df.iloc[-3:]

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
3  April           80            80            54          180  6:00
4    May           51            54            54          154  7:00
5   June          112           109            79          129  8:00

In [70]:
df[df.month == 'April']

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
3  April           80            80            54          180  6:00

In [78]:
df[df.Time != '6:00']

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
0   January          100           100            23          100  3:00
1  February           51            45           145           45  4:00
2     March           81            96            65           96  5:00
4       May           51            54            54          154  7:00
5      June          112           109            79          129  8:00

In [79]:
df[df.clinic_east <= 81]

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
1  February           51            45           145           45  4:00
2     March           81            96            65           96  5:00
3     April           80            80            54          180  6:00
4       May           51            54            54          154  7:00

In [72]:
df[(df.month == 'May') & (df.clinic_east == 51)] # used of AND Operator

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
4   May           51            54            54          154  7:00

In [81]:
df[(df.month == 'May') | (df.clinic_east == 80)] # use of OR operator

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
3  April           80            80            54          180  6:00
4    May           51            54            54          154  7:00

In [86]:
df3 = df[df.month.isin(['May', 'June', 'July'])]
df3

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
4   May           51            54            54          154  7:00
5  June          112           109            79          129  8:00

In [88]:
df3.reset_index()

index month  clinic_east  clinic_north  clinic_south  clinic_west  Time
0      4   May           51            54            54          154  7:00
1      5  June          112           109            79          129  8:00

In [90]:
df3.reset_index(inplace = True , drop = True)
df3

month  clinic_east  clinic_north  clinic_south  clinic_west  Time
0   May           51            54            54          154  7:00
1  June          112           109            79          129  8:00

# Shoefly Dataset

In [92]:
df2 = pd.read_csv('shoefly.csv')

In [93]:
df2

id  first_name   last_name                         email     shoe_type  \
0   54791     Rebecca     Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1   53450       Emily       Joyce        EmilyJoyce25@gmail.com  ballet flats   
2   91987       Joyce      Waller        Joyce.Waller@gmail.com       sandals   
3   14437      Justin    Erickson   Justin.Erickson@outlook.com         clogs   
4   79357      Andrew       Banks              AB4318@gmail.com         boots   
5   52386       Julie       Marsh        JulieMarsh59@gmail.com       sandals   
6   20487      Thomas      Jensen              TJ5470@gmail.com         clogs   
7   76971      Janice       Hicks        Janice.Hicks@gmail.com         clogs   
8   21586     Gabriel      Porter     GabrielPorter24@gmail.com         clogs   
9   62083     Frances      Palmer     FrancesPalmer50@gmail.com        wedges   
10  91629     Jessica        Hale       JessicaHale25@gmail.com         clogs   
11  98602    Lawrence      Parker    LawrenceParker44@gmail.com        wedges   
12  45832       Susan      Dennis       SusanDennis58@gmail.com  ballet flats   
13  33862       Diane       Ochoa              DO2680@gmail.com       sandals   
14  73431     Rebecca     Charles     Rebecca.Charles@gmail.com         boots   
15  93889  Jacqueline       Crane            JC2072@hotmail.com        wedges   
16  39888     Vincent  Stephenson            VS4753@outlook.com         boots   
17  35961         Roy     Tillman        RoyTillman20@gmail.com         boots   
18  24560      Thomas    Roberson     Thomas.Roberson@gmail.com        wedges   
19  28559      Angela      Newton       ANewton1977@outlook.com        wedges   

   shoe_material shoe_color  
0   faux-leather      black  
1   faux-leather       navy  
2         fabric      black  
3   faux-leather        red  
4        leather      brown  
5         fabric      black  
6         fabric       navy  
7   faux-leather       navy  
8        leather      brown  
9        leather      white  
10       leather        red  
11        fabric      brown  
12        fabric      white  
13        fabric        red  
14  faux-leather      white  
15        fabric        red  
16       leather      black  
17       leather      white  
18        fabric        red  
19        fabric        red

### Basic Three Operation head(), info(), describe()

In [94]:
df2.head(6)

id first_name last_name                         email     shoe_type  \
0  54791    Rebecca   Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1  53450      Emily     Joyce        EmilyJoyce25@gmail.com  ballet flats   
2  91987      Joyce    Waller        Joyce.Waller@gmail.com       sandals   
3  14437     Justin  Erickson   Justin.Erickson@outlook.com         clogs   
4  79357     Andrew     Banks              AB4318@gmail.com         boots   
5  52386      Julie     Marsh        JulieMarsh59@gmail.com       sandals   

  shoe_material shoe_color  
0  faux-leather      black  
1  faux-leather       navy  
2        fabric      black  
3  faux-leather        red  
4       leather      brown  
5        fabric      black

In [95]:
df2.describe()

id
count     20.000000
mean   54687.400000
std    27431.097628
min    14437.000000
25%    32536.250000
50%    52918.000000
75%    77567.500000
max    98602.000000

In [96]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   id             20 non-null     int64 
 1   first_name     20 non-null     object
 2   last_name      20 non-null     object
 3   email          20 non-null     object
 4   shoe_type      20 non-null     object
 5   shoe_material  20 non-null     object
 6   shoe_color     20 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.2+ KB


In [97]:
df2.count()

id               20
first_name       20
last_name        20
email            20
shoe_type        20
shoe_material    20
shoe_color       20
dtype: int64

### Column selection

In [101]:
print(df2.first_name)  
print('---------------')
df2['first_name']

0        Rebecca
1          Emily
2          Joyce
3         Justin
4         Andrew
5          Julie
6         Thomas
7         Janice
8        Gabriel
9        Frances
10       Jessica
11      Lawrence
12         Susan
13         Diane
14       Rebecca
15    Jacqueline
16       Vincent
17           Roy
18        Thomas
19        Angela
Name: first_name, dtype: object
---------------


0        Rebecca
1          Emily
2          Joyce
3         Justin
4         Andrew
5          Julie
6         Thomas
7         Janice
8        Gabriel
9        Frances
10       Jessica
11      Lawrence
12         Susan
13         Diane
14       Rebecca
15    Jacqueline
16       Vincent
17           Roy
18        Thomas
19        Angela
Name: first_name, dtype: object

In [102]:
type(df2['first_name'])

pandas.core.series.Series

### Multiple Column Selection

In [145]:
df2[['first_name', 'last_name']].head() # multiple column selection

first_name last_name
0    Rebecca   Lindsay
1      Emily     Joyce
2      Joyce    Waller
3     Justin  Erickson
4     Andrew     Banks

In [109]:
type(df2[['first_name', 'last_name']])

pandas.core.frame.DataFrame

### Rows Selection with loc[ ] and iloc[ ]

In [113]:
df2.iloc[0]

id                                      54791
first_name                            Rebecca
last_name                             Lindsay
email            RebeccaLindsay57@hotmail.com
shoe_type                               clogs
shoe_material                    faux-leather
shoe_color                              black
Name: 0, dtype: object

In [114]:
df2.loc[0]

id                                      54791
first_name                            Rebecca
last_name                             Lindsay
email            RebeccaLindsay57@hotmail.com
shoe_type                               clogs
shoe_material                    faux-leather
shoe_color                              black
Name: 0, dtype: object

In [115]:
df2.iloc[[1,2,3]]

id first_name last_name                        email     shoe_type  \
1  53450      Emily     Joyce       EmilyJoyce25@gmail.com  ballet flats   
2  91987      Joyce    Waller       Joyce.Waller@gmail.com       sandals   
3  14437     Justin  Erickson  Justin.Erickson@outlook.com         clogs   

  shoe_material shoe_color  
1  faux-leather       navy  
2        fabric      black  
3  faux-leather        red

In [116]:
df2.loc[[1,2,3]]

id first_name last_name                        email     shoe_type  \
1  53450      Emily     Joyce       EmilyJoyce25@gmail.com  ballet flats   
2  91987      Joyce    Waller       Joyce.Waller@gmail.com       sandals   
3  14437     Justin  Erickson  Justin.Erickson@outlook.com         clogs   

  shoe_material shoe_color  
1  faux-leather       navy  
2        fabric      black  
3  faux-leather        red

In [117]:
df2.iloc[2:5]

id first_name last_name                        email shoe_type  \
2  91987      Joyce    Waller       Joyce.Waller@gmail.com   sandals   
3  14437     Justin  Erickson  Justin.Erickson@outlook.com     clogs   
4  79357     Andrew     Banks             AB4318@gmail.com     boots   

  shoe_material shoe_color  
2        fabric      black  
3  faux-leather        red  
4       leather      brown

In [118]:
df2.loc[2:5]

id first_name last_name                        email shoe_type  \
2  91987      Joyce    Waller       Joyce.Waller@gmail.com   sandals   
3  14437     Justin  Erickson  Justin.Erickson@outlook.com     clogs   
4  79357     Andrew     Banks             AB4318@gmail.com     boots   
5  52386      Julie     Marsh       JulieMarsh59@gmail.com   sandals   

  shoe_material shoe_color  
2        fabric      black  
3  faux-leather        red  
4       leather      brown  
5        fabric      black

In [119]:
df2.iloc[-2]

id                                   24560
first_name                          Thomas
last_name                         Roberson
email            Thomas.Roberson@gmail.com
shoe_type                           wedges
shoe_material                       fabric
shoe_color                             red
Name: 18, dtype: object

In [120]:
df2.loc[-2] # Error is the real answer b/c loc didn't know -ve indexces

KeyError: -2

In [121]:
df2.iloc[-3:] # right answer

id first_name last_name                      email shoe_type  \
17  35961        Roy   Tillman     RoyTillman20@gmail.com     boots   
18  24560     Thomas  Roberson  Thomas.Roberson@gmail.com    wedges   
19  28559     Angela    Newton    ANewton1977@outlook.com    wedges   

   shoe_material shoe_color  
17       leather      white  
18        fabric        red  
19        fabric        red

In [123]:
df2.loc[-3:] #wrong answer accordind to the logic

id  first_name   last_name                         email     shoe_type  \
0   54791     Rebecca     Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1   53450       Emily       Joyce        EmilyJoyce25@gmail.com  ballet flats   
2   91987       Joyce      Waller        Joyce.Waller@gmail.com       sandals   
3   14437      Justin    Erickson   Justin.Erickson@outlook.com         clogs   
4   79357      Andrew       Banks              AB4318@gmail.com         boots   
5   52386       Julie       Marsh        JulieMarsh59@gmail.com       sandals   
6   20487      Thomas      Jensen              TJ5470@gmail.com         clogs   
7   76971      Janice       Hicks        Janice.Hicks@gmail.com         clogs   
8   21586     Gabriel      Porter     GabrielPorter24@gmail.com         clogs   
9   62083     Frances      Palmer     FrancesPalmer50@gmail.com        wedges   
10  91629     Jessica        Hale       JessicaHale25@gmail.com         clogs   
11  98602    Lawrence      Parker    LawrenceParker44@gmail.com        wedges   
12  45832       Susan      Dennis       SusanDennis58@gmail.com  ballet flats   
13  33862       Diane       Ochoa              DO2680@gmail.com       sandals   
14  73431     Rebecca     Charles     Rebecca.Charles@gmail.com         boots   
15  93889  Jacqueline       Crane            JC2072@hotmail.com        wedges   
16  39888     Vincent  Stephenson            VS4753@outlook.com         boots   
17  35961         Roy     Tillman        RoyTillman20@gmail.com         boots   
18  24560      Thomas    Roberson     Thomas.Roberson@gmail.com        wedges   
19  28559      Angela      Newton       ANewton1977@outlook.com        wedges   

   shoe_material shoe_color  
0   faux-leather      black  
1   faux-leather       navy  
2         fabric      black  
3   faux-leather        red  
4        leather      brown  
5         fabric      black  
6         fabric       navy  
7   faux-leather       navy  
8        leather      brown  
9        leather      white  
10       leather        red  
11        fabric      brown  
12        fabric      white  
13        fabric        red  
14  faux-leather      white  
15        fabric        red  
16       leather      black  
17       leather      white  
18        fabric        red  
19        fabric        red

### Specific Row Selction with some Logic

In [124]:
df2[df2.first_name == 'Angela']

id first_name last_name                    email shoe_type  \
19  28559     Angela    Newton  ANewton1977@outlook.com    wedges   

   shoe_material shoe_color  
19        fabric        red

In [126]:
df2[df2.shoe_type != 'boots' ]

id  first_name last_name                         email     shoe_type  \
0   54791     Rebecca   Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1   53450       Emily     Joyce        EmilyJoyce25@gmail.com  ballet flats   
2   91987       Joyce    Waller        Joyce.Waller@gmail.com       sandals   
3   14437      Justin  Erickson   Justin.Erickson@outlook.com         clogs   
5   52386       Julie     Marsh        JulieMarsh59@gmail.com       sandals   
6   20487      Thomas    Jensen              TJ5470@gmail.com         clogs   
7   76971      Janice     Hicks        Janice.Hicks@gmail.com         clogs   
8   21586     Gabriel    Porter     GabrielPorter24@gmail.com         clogs   
9   62083     Frances    Palmer     FrancesPalmer50@gmail.com        wedges   
10  91629     Jessica      Hale       JessicaHale25@gmail.com         clogs   
11  98602    Lawrence    Parker    LawrenceParker44@gmail.com        wedges   
12  45832       Susan    Dennis       SusanDennis58@gmail.com  ballet flats   
13  33862       Diane     Ochoa              DO2680@gmail.com       sandals   
15  93889  Jacqueline     Crane            JC2072@hotmail.com        wedges   
18  24560      Thomas  Roberson     Thomas.Roberson@gmail.com        wedges   
19  28559      Angela    Newton       ANewton1977@outlook.com        wedges   

   shoe_material shoe_color  
0   faux-leather      black  
1   faux-leather       navy  
2         fabric      black  
3   faux-leather        red  
5         fabric      black  
6         fabric       navy  
7   faux-leather       navy  
8        leather      brown  
9        leather      white  
10       leather        red  
11        fabric      brown  
12        fabric      white  
13        fabric        red  
15        fabric        red  
18        fabric        red  
19        fabric        red

In [128]:
df2[(df2.shoe_type != 'boots') & (df2.shoe_material == 'leather') ]

id first_name last_name                      email shoe_type  \
8   21586    Gabriel    Porter  GabrielPorter24@gmail.com     clogs   
9   62083    Frances    Palmer  FrancesPalmer50@gmail.com    wedges   
10  91629    Jessica      Hale    JessicaHale25@gmail.com     clogs   

   shoe_material shoe_color  
8        leather      brown  
9        leather      white  
10       leather        red

In [129]:
df2[(df2.first_name == 'Angela') | (df2.last_name == 'Dennis')]

id first_name last_name                    email     shoe_type  \
12  45832      Susan    Dennis  SusanDennis58@gmail.com  ballet flats   
19  28559     Angela    Newton  ANewton1977@outlook.com        wedges   

   shoe_material shoe_color  
12        fabric      white  
19        fabric        red

In [130]:
df2[(df2.first_name == 'Angela') | (df2.last_name == 'Qasim Hassan')] # because is not present

id first_name last_name                    email shoe_type  \
19  28559     Angela    Newton  ANewton1977@outlook.com    wedges   

   shoe_material shoe_color  
19        fabric        red

In [143]:
df.iloc[20] # out of order Error Arises

IndexError: single positional indexer is out-of-bounds

In [132]:
df.loc[20] # out of range Erroer arises

KeyError: 20

In [135]:
df2[df2.first_name.isin(['Angela', 'Qasim'])]  #---->>> IMPORTANT

id first_name last_name                    email shoe_type  \
19  28559     Angela    Newton  ANewton1977@outlook.com    wedges   

   shoe_material shoe_color  
19        fabric        red

In [138]:
df3 = df2[(df2.first_name.isin(['Angela', 'Qasim'])) | (df2.last_name.isin(['Dennis', 'Hassan']))]

In [139]:
df3

id first_name last_name                    email     shoe_type  \
12  45832      Susan    Dennis  SusanDennis58@gmail.com  ballet flats   
19  28559     Angela    Newton  ANewton1977@outlook.com        wedges   

   shoe_material shoe_color  
12        fabric      white  
19        fabric        red

### Reseting Indexes

In [140]:
df3.reset_index()

index     id first_name last_name                    email     shoe_type  \
0     12  45832      Susan    Dennis  SusanDennis58@gmail.com  ballet flats   
1     19  28559     Angela    Newton  ANewton1977@outlook.com        wedges   

  shoe_material shoe_color  
0        fabric      white  
1        fabric        red

In [141]:
df3.reset_index(inplace = True , drop = True)

In [142]:
df3

id first_name last_name                    email     shoe_type  \
0  45832      Susan    Dennis  SusanDennis58@gmail.com  ballet flats   
1  28559     Angela    Newton  ANewton1977@outlook.com        wedges   

  shoe_material shoe_color  
0        fabric      white  
1        fabric        red