In [1]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [2]:
%history

%lsmagic
%history


In [3]:
import numpy as np

In [14]:
%time t = [x+5 for x in range(100000000)][:20000]

Wall time: 12.8 s


In [15]:
data = ['Qasim', 'Hassan']
list(enumerate(data))

[(0, 'Qasim'), (1, 'Hassan')]

In [6]:
l1 = list(range(1000000))
for i in enumerate(l1):
    l1[i[0]] += 5
l1[:5]    

%time

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.82 µs


In [22]:
l1[:5]

[5, 6, 7, 8, 9]

In [23]:
l1 = np.arange(10000000) + 5 # numpy array
l1[:20000]
%time

Wall time: 0 ns


In [24]:
list(enumerate([1,2,3]))

[(0, 1), (1, 2), (2, 3)]

In [25]:
l2 = [[1,3,2],
     [4,5,6],
     [7,8,9]]
print(type(l2)) # two dimension list
l2

<class 'list'>


[[1, 3, 2], [4, 5, 6], [7, 8, 9]]

In [10]:
l2 + 5

TypeError: can only concatenate list (not "int") to list

In [12]:
l2 = [[1,3,2],
     [4,5,6],
     [7,8,9]]

for r in enumerate(l2):
    for c in enumerate(l2[r[0]]):
        l2[r[0]][c[0]] += 5
%time        
l2        

CPU times: user 3 µs, sys: 2 µs, total: 5 µs
Wall time: 10 µs


[[6, 8, 7], [9, 10, 11], [12, 13, 14]]

# Now checke with numpy 

In [29]:
l2 = [[1,3,2],
     [4,5,6],
     [7,8,9]]
print(type(l2))
l2 = np.array(l2)
print(type(l2))
print(l2)

<class 'list'>
<class 'numpy.ndarray'>
[[1 3 2]
 [4 5 6]
 [7 8 9]]


In [30]:
#l2 + 5
#l2 - 5
print(l2 + 5)
%time

[[ 6  8  7]
 [ 9 10 11]
 [12 13 14]]
Wall time: 0 ns


In [37]:
np.arange(100000000)+5

array([        5,         6,         7, ..., 100000002, 100000003,
       100000004])

In [38]:
l3 = np.arange(10*10*3).reshape((10,10,3))  #np.arange('firstdim', 'seconddim', 'thirddim') row,column,channel
print(l3 + 5)
%time

[[[  5   6   7]
  [  8   9  10]
  [ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]
  [ 20  21  22]
  [ 23  24  25]
  [ 26  27  28]
  [ 29  30  31]
  [ 32  33  34]]

 [[ 35  36  37]
  [ 38  39  40]
  [ 41  42  43]
  [ 44  45  46]
  [ 47  48  49]
  [ 50  51  52]
  [ 53  54  55]
  [ 56  57  58]
  [ 59  60  61]
  [ 62  63  64]]

 [[ 65  66  67]
  [ 68  69  70]
  [ 71  72  73]
  [ 74  75  76]
  [ 77  78  79]
  [ 80  81  82]
  [ 83  84  85]
  [ 86  87  88]
  [ 89  90  91]
  [ 92  93  94]]

 [[ 95  96  97]
  [ 98  99 100]
  [101 102 103]
  [104 105 106]
  [107 108 109]
  [110 111 112]
  [113 114 115]
  [116 117 118]
  [119 120 121]
  [122 123 124]]

 [[125 126 127]
  [128 129 130]
  [131 132 133]
  [134 135 136]
  [137 138 139]
  [140 141 142]
  [143 144 145]
  [146 147 148]
  [149 150 151]
  [152 153 154]]

 [[155 156 157]
  [158 159 160]
  [161 162 163]
  [164 165 166]
  [167 168 169]
  [170 171 172]
  [173 174 175]
  [176 177 178]
  [179 180 181]
  [182 183 184]]

 [[185 186 187]
  [188 189 1

In [41]:
l3.ndim #tensor,rank,dimension

3

In [42]:
l3 = np.arange(300)
l3 = l3.reshape((2,150))
l3

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       

In [43]:
l3.ndim # now it is 2d tensor, 2 rank or 2 dimentional

2

In [44]:

np.arange(1,11,2) 

array([1, 3, 5, 7, 9])

In [45]:
l1 = np.arange(1,11)
print(l1)
print(type(l1))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [46]:
l1.ndim

1

In [47]:
l1.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])