In [230]:
import numpy as np
from PIL import Image
image1 = Image.open('2.jpg')
print(image1.format)
print(image1.size)

JPEG
(500, 500)


In [231]:
data = np.asarray(image1)
data.shape

(500, 500, 3)

In [232]:
filter = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]])

In [233]:
data.shape[0]

500

In [234]:
data1 = np.array(data)

In [235]:
for i in range(data.shape[0]):
    for x in range(data.shape[1]):
                    data1[i,x:x+3,::] = np.dot(data[i,x:x+3,::],filter)
        

In [236]:
result = Image.fromarray(data1, 'RGB')
result.save('task41.png')


In [261]:
image2 = Image.open('2.jpg')
data2 = np.asarray(image2)
data2.shape
filter2 = np.array([
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1]])
data3 = np.array(data2)

for i in range(data2.shape[0]):
    for x in range(0,data2.shape[1],3):
                    data3[i,x:x+3,::] = np.dot(data2[i,x:x+3,::],filter2)

result = Image.fromarray(data3, 'RGB')
result.save('task42.png')


In [255]:
data3

array([[[ 34,   0, 222],
        [ 32,   0, 224],
        [ 29,   0, 227],
        ...,
        [175,   0,  81],
        [175,   0,  81],
        [175,   0,  81]],

       [[ 40,   0, 216],
        [ 34,   0, 222],
        [ 29,   0, 227],
        ...,
        [175,   0,  81],
        [175,   0,  81],
        [175,   0,  81]],

       [[ 40,   0, 216],
        [ 37,   0, 219],
        [ 29,   0, 227],
        ...,
        [175,   0,  81],
        [175,   0,  81],
        [175,   0,  81]],

       ...,

       [[152,   0, 104],
        [134,   0, 122],
        [107,   0, 149],
        ...,
        [113,   0, 143],
        [119,   0, 137],
        [125,   0, 131]],

       [[155,   0, 101],
        [113,   0, 143],
        [ 65,   0, 191],
        ...,
        [110,   0, 146],
        [116,   0, 140],
        [122,   0, 134]],

       [[152,   0, 104],
        [ 95,   0, 161],
        [ 38,   0, 218],
        ...,
        [ 95,   0, 161],
        [104,   0, 152],
        [110,   0, 146]]

In [221]:
data1

array([[[ 34,   0, 222],
        [ 32,   0, 224],
        [ 29,   0, 227],
        ...,
        [175,   0,  81],
        [175,   0,  81],
        [175,   0,  81]],

       [[ 40,   0, 216],
        [ 34,   0, 222],
        [ 29,   0, 227],
        ...,
        [175,   0,  81],
        [175,   0,  81],
        [175,   0,  81]],

       [[ 40,   0, 216],
        [ 37,   0, 219],
        [ 29,   0, 227],
        ...,
        [175,   0,  81],
        [175,   0,  81],
        [175,   0,  81]],

       ...,

       [[ 40,  38,  26],
        [ 46,  44,  32],
        [ 55,  53,  41],
        ...,
        [145, 133, 121],
        [143, 131, 119],
        [141, 129, 117]],

       [[ 39,  37,  25],
        [ 53,  51,  39],
        [ 69,  67,  55],
        ...,
        [146, 134, 122],
        [144, 132, 120],
        [142, 130, 118]],

       [[ 40,  38,  26],
        [ 59,  57,  45],
        [ 78,  76,  64],
        ...,
        [151, 139, 127],
        [148, 136, 124],
        [146, 134, 122]]

In [71]:
y=0
x=499
#data1[x,y,0]
data1[x:-3,y:y+3,0] 
#=  np.dot(data[x:x-3,y:y+3,i],filter)

array([], shape=(0, 3), dtype=uint8)

In [79]:
dx = True
x=8500
while dx:
    if(x % 3 == 0):
        dx = False
    else:
        x =x+1
print(x,x%3)     

8502 0


In [82]:
data1[499:500+3,499:500+3,::] = 0

In [83]:
data1.shape

(500, 500, 3)

In [89]:
data1[499,::,::]

array([[ 40,  38,  26],
       [ 59,  57,  45],
       [ 78,  76,  64],
       ...,
       [151, 139, 127],
       [148, 136, 124],
       [146, 134, 122]], dtype=uint8)

In [147]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
b = np.int64(np.zeros((3,1)))
c = np.int64(np.zeros((1,4)))
b

array([[0],
       [0],
       [0]], dtype=int64)

In [153]:
a = np.hstack((a,b))
a = np.vstack((a,c))

In [154]:
a

array([[0, 1, 2, 0],
       [3, 4, 5, 0],
       [6, 7, 8, 0],
       [0, 0, 0, 0]], dtype=int64)

In [155]:
data.shape

(500, 500, 3)

In [183]:
data1.shape

(500, 500, 3)

In [184]:
addx = np.int32(np.zeros((500,3)))
addy = np.int32(np.zeros((3,500)))
data1[0] = np.hstack((data1,addx))
data1[0] = np.vstack((data1,addy))

ValueError: all the input arrays must have same number of dimensions

In [179]:
b = np.int64(np.arange(3*3*1).reshape(3,3,1))

In [188]:
data1[0]

array([[91, 71, 60],
       [93, 71, 60],
       [94, 72, 61],
       ...,
       [35, 23, 23],
       [35, 23, 23],
       [35, 23, 23]], dtype=uint8)

In [191]:
c = np.arange(500*500*3).reshape(500,500,3)

In [202]:
c[499]

array([[748500, 748501, 748502],
       [748503, 748504, 748505],
       [748506, 748507, 748508],
       ...,
       [749991, 749992, 749993],
       [749994, 749995, 749996],
       [749997, 749998, 749999]])

In [193]:
c.shape

(500, 500, 3)

In [209]:
c[0,:3,:3]*filter
#c[slides,rows,colums]

array([[ 0,  0,  2],
       [-3,  0,  5],
       [-6,  0,  8]])

In [212]:
o=499
l = 499
c[0,o-3:o,::]

array([[1488, 1489, 1490],
       [1491, 1492, 1493],
       [1494, 1495, 1496]])