In [2]:
print("Helloworld")

Helloworld


In [1]:
print("Line1")
print("Line2")

Line1
Line2


In [3]:
%history

print("Line1")
print("Line2")
print("Helloworld")
%history


In [4]:
# %load xyz.py
print("Line1")
print("Line2")
print("Line3")
print("From other file")


Line1
Line2
Line3
From other file


In [5]:
%run xyz.py

Line1
Line2
Line3
From other file


In [6]:
%time print("ada")

ada
Wall time: 0 ns


# Python

In [7]:
%time l1 = list(range(1,3000000))
print(l1[:10])

Wall time: 67.8 ms
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
%time [x+5 for x in l1][:10]

Wall time: 303 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [9]:
for i, e in list(enumerate(l1)):
    l1[i] = l1[i] + 5
l1[:10]    

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [10]:
for i, e in list(enumerate(l1)):
    l1[i] += 5
l1[:10]  

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
l1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print("Before Adding 5")
print(l1)
print()
for ri, rd in list(enumerate(l1)):
    for ci, cd in list(enumerate(rd)):
        l1[ri][ci] += 5
print("After Adding 5")
print(l1)

In [ ]:
l1 = [1,2,4]
l1 + 5

# Numpy 

In [11]:
def abc():print("pakistan") #python
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [2]:
# import numpy as *
import numpy as np

In [13]:
l = [1,3,2]
print(sum(l)) # python function
print(np.sum(l)) # Numpy function

6
6


In [14]:
l1 = np.arange(1,3000000)
%time l1 + 5

Wall time: 8 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [15]:
l1 = np.arange(1,13)


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 1
Type: int32
Size: 12
Itemsize: 4
Shape: (12,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
l1 = np.array(1)


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 0
Type: int32
Size: 1
Itemsize: 4
Shape: ()


array(1)

In [18]:
# 1D array
l1 = np.array([1,5])


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 1
Type: int32
Size: 2
Itemsize: 4
Shape: (2,)


array([1, 5])

In [19]:
# 2D array
l1 = np.array([[1,5],
               [8,9]])


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 2
Type: int32
Size: 4
Itemsize: 4
Shape: (2, 2)


array([[1, 5],
       [8, 9]])

In [16]:
np.array??

# A Multidimensional Array Object

In [3]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
# -1 represent remaining data
# 6 is row
np.arange(1,13).reshape((6,-1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
np.arange(1,13).reshape((4,-1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
 #l1 = np.arange(1,13).reshape((4,3))
# l1 = np.arange(1,13).reshape((3,4))
# l1 = np.arange(1,13).reshape((2,6))
# l1 = np.arange(1,13).reshape((6,2))
# l1 = np.arange(1,13).reshape((12,1))

l1 = np.arange(1,13).reshape((6,-1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (6, 2)


In [8]:
l1 = np.arange(1,13).reshape((6,-1))
l1.shape = (2,6)
l1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

<img src="https://www.pythoninformer.com/img/numpy/3d-array-stack.png">
<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

In [9]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int32
Size: 27
Itemsize: 4
Shape: (3, 3, 3)


In [10]:
np.arange(4*3*2*2).reshape((4,3,2,2))

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]]]])

In [12]:
np.arange(3*2*3*2*2).reshape((3,2,3,2,2))

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]],



       [[[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]],

         [[32, 33],
          [34, 35]]],


        [[[36, 37],
          [38, 39]],

         [[40, 41],
          [42, 43]],

         [[44, 45],
          [46, 47]]]],



       [[[[48, 49],
          [50, 51]],

         [[52, 53],
          [54, 55]],

         [[56, 57],
          [58, 59]]],


        [[[60, 61],
          [62, 63]],

         [[64, 65],
          [66, 67]],

         [[68, 69],
          [70, 71]]]]])

In [13]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
# l1[i,j,k]
# l1[slide, row, column]
# l1[2]
# l1[1,2]
l1[1,2,1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


17

In [14]:
l1[1][2][0]

16

In [15]:
l1 = np.array(['a','b','c'])
print(l1)
#   0      1      2
l1[[True, False, True]]

['a' 'b' 'c']


array(['a', 'c'], dtype='<U1')

In [18]:
ages = np.arange(1,80)
jawan = []
for age in ages:
    if age > 25:
        jawan.append(True)
    else:
        jawan.append(False)
    
jawan

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [19]:
ages[jawan]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [21]:
ages[ages > 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [23]:
ages= list(range(1,100))
print(type(ages))
ages

<class 'list'>


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [24]:
# This opreation is not supported in list
ages[ages > 25]

TypeError: '>' not supported between instances of 'list' and 'int'

In [25]:
l1 = np.arange(1,28).reshape((3,3,3))
print(l1)
l1[l1 % 6 == 0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 6, 12, 18, 24])

In [26]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print(l1[l1 % 3 == 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 3  6  9 12 15 18 21 24 27]


In [27]:
l1 % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [30]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
l1[(l1 % 3 == 0)  & (l1 % 9 == 0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 9, 18, 27])

In [31]:
l1 = np.random.randn(3,3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[[ 1.04725748  0.65399846 -0.44736759]
   [-1.59796347 -0.17352479 -0.20983283]
   [-3.04050852 -0.96527261 -0.65316936]]

  [[-0.43480611 -0.0965851  -0.54658819]
   [-0.5553209  -2.01671929 -1.53758011]
   [ 0.267692    1.38370185  0.08954641]]

  [[ 0.21640243 -0.94441645  0.8982768 ]
   [-1.36985426  1.63322461  0.05067112]
   [-0.95588714  0.63802627 -0.50104964]]]


 [[[ 1.70122731 -0.15127754 -0.85044111]
   [-0.09648863 -0.04384449 -0.43933995]
   [-0.13812089  0.43831461 -0.79992703]]

  [[-0.34859829  0.22798332  0.61552581]
   [ 0.13818522  1.0451642   0.91255951]
   [-0.06877916 -0.54194454  1.63839795]]

  [[ 0.7624983   0.09446874 -0.60629275]
   [ 0.10350566 -0.58266009 -0.28053853]
   [ 0.47625899  0.46286298 -0.10043574]]]


 [[[-1.73760785  0.06080503  1.73190416]
   [ 1.50615335  1.18080662 -0.33561917]
   [-0.63822067  0.26270706  0.09860268]]

  [[-0.17528278  0.91001984 -0.18157026]
   [ 1.37169878 -0.37181072 -1.03546417]
   [ 1.97830263 -1.65160884 -1.96190713

In [ ]:
# l1 + 2
# l1 * 2
#l1 / 2
#l1 ** 2
#l1 ** 0.5
#l1 % 2

# Creating ndarrays

##### np.array()

In [33]:
# Deep Copy(Always copy)
l = [1,2,3]

a = np.array(l)
b = np.array(a)

print(a is l) #False
print(b is a) #False
print(a is a)
print(id(a) == id(a))
print(id(a) == id(b))

False
False
True
True
False


In [34]:
# 1 array->Same Datatype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1 
c = np.asarray(a, dtype=np.float64)#2

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [35]:
import numpy as np
a = np.array([1,2])
a.itemsize

4

In [ ]:
import numpy as np

## Creating ndarrays

In [38]:
a = np.array([1,3,4])
b = np.asarray([1,3,5])
print(a)
print(b)

[1 3 4]
[1 3 5]


In [39]:
a = np.arange(1,14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

# Chaining

In [41]:
range??

In [43]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7    

In [44]:
C(B(A(1))) #1+5=6  6+6=12 12+7=19

19

In [45]:
A(B(C(1)))

19

np.A().B().C()

In [ ]:
#arange().reshape()
#np.ones
#np.ones_like
#np.zeros
#np.zeros_like
#np.full
#np.full_like
#np.empty
#np.empty_like

In [6]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [47]:
b = np.reshape(a, (27,1))
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [52]:
a = np.arange(1,28)
a.reshape(3,3,3)
print(a)
print(a.ndim)
a.shape = (3,9)
#a = a.reshape(3,3,3)
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [53]:
a.shape = (3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
a.shape = (3,9)

In [61]:
a.shape

(3, 9)

In [58]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
a.shape[0]

3

In [62]:
np.zeros((a.shape[0], a.shape[1]))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
np.zeros((a.shape))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
np.zeros(a.shape)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [73]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
a

NameError: name 'a' is not defined

In [76]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
b = np.ones_like(a)
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [78]:
b = np.ones_like(a) * 5 # + 5
b

array([[5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [1]:
import numpy as np

b = np.full((3,3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [2]:
import numpy as np

b = np.full([3,3], 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
import numpy as np

b = np.full({3,5}, 5)
b

TypeError: 'set' object does not support indexing

In [ ]:
# checkpoint 3-5-2021

In [8]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [7]:
b = np.full_like(a, 5)
b

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [9]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [11]:
np.full_like(a, dtype=a.dtype, fill_value=2.6)

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [12]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([[[2.5, 2.5, 2.5],
        [2.5, 2.5, 2.5],
        [2.5, 2.5, 2.5]],

       [[2.5, 2.5, 2.5],
        [2.5, 2.5, 2.5],
        [2.5, 2.5, 2.5]],

       [[2.5, 2.5, 2.5],
        [2.5, 2.5, 2.5],
        [2.5, 2.5, 2.5]]])

In [15]:
np.empty((3,9)) # garbage values

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [14]:
np.empty_like(a)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [16]:
np.full_like(a, 1) * np.nan

array([[[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]]])

In [17]:
np.full(a.shape, np.nan)

array([[[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]]])

In [18]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types for ndarrays

In [20]:
a = np.array([1,3,4], dtype='int')
a.dtype

dtype('int32')

In [21]:
a = np.array([1,3,4], dtype=int)
a.dtype

dtype('int32')

In [22]:
a = np.array([1,3,4], dtype=np.int64)
a.dtype

dtype('int64')

In [23]:
a = np.array([1,3,4], dtype='i1') #integer of 8 bits
a.dtype

dtype('int8')

In [24]:
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

dtype('int8')

In [25]:
c = a.astype(np.int64)
c.dtype

dtype('int64')

In [27]:
c = a.astype(np.float64)
print(c)
c.dtype


[1. 3. 4.]


dtype('float64')

In [28]:
c = a.astype(np.int64)
print(c)
c.dtype

[1 3 4]


dtype('int64')

In [29]:
c = a.astype(np.int8)
print(c)
c.dtype

[1 3 4]


dtype('int8')

In [32]:
c = [2.1, 2.3 , 4.5, 7.8]
d = np.array(c)
d.astype(np.int8)

array([2, 2, 4, 7], dtype=int8)

In [33]:
a = 3.7
int(a)

3

# Boolen Operation

In [34]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [35]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [36]:
print(a)
a[a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [37]:
print(a)
a[(a%3==0) & (a%5==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [40]:
~(a%3==0)

array([[[ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]],

       [[ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]],

       [[ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]]])

In [41]:
print(a)
a[~(a%3==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [42]:
print(a)
a[a%3!=0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [43]:
a = np.arange(1,7).reshape((2,3,1))
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

# Fancy Slicing

In [44]:
import numpy as np

In [46]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[2,0,1]] #slide adjustment


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [59]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print("=====")
# print(a[[1,2,0]])
# print(a[[1,2,0]])
# a[[0,1,2],[0,1,2]]
# a[[2,1,0],[0,1,2]]
# a[[0,1,2],:,[0,1,2]].T
# a[[1,2,0]][:,[2,1,0]]
# a[[0,1,2]][:,[-1,0]]
# a[[1,2,0],:,::-1]
# a[::-1]
a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]
=====


array([[[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]],

       [[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]]])

In [60]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Hassan","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Hassan' 'Abid']


[[-0.19523298 -0.14746074  1.83208443  0.61300999]
 [ 0.68925354 -0.17875674 -1.00739384  0.33272624]
 [-0.06155634 -1.31566945  1.42209508  0.44775452]
 [ 0.21632868  1.60761398  0.92859959 -1.73320481]
 [-0.96083114  0.03542983 -0.45387366 -0.21796286]
 [ 0.56454649  0.53668544  0.6072207  -0.68298747]]


In [61]:
names == "Qasim"

array([ True, False, False, False, False, False])

In [62]:
data[[ True, False, False, False,  True, False]]

array([[-0.19523298, -0.14746074,  1.83208443,  0.61300999],
       [-0.96083114,  0.03542983, -0.45387366, -0.21796286]])

In [64]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Hassan","Abid"])

data1 = np.random.randn(4,6)
print(names, data1, sep="\n\n\n")

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Hassan' 'Abid']


[[ 0.21907004 -0.04640316 -1.6029605  -1.01842374 -0.26896777 -1.75559651]
 [ 0.57501757 -0.2142508   1.46079768  1.33215045  0.82504974  1.24648658]
 [-0.30574401  0.98567085  0.36835192 -0.45396008 -0.763318   -0.89045843]
 [-0.03896102  0.1970787   0.60756116 -0.29933939 -0.03843332  1.2438799 ]]


In [68]:
(names=='Qasim') | (names == 'Hassan')

array([ True, False, False, False,  True, False])

In [71]:
data1[:,(names=='Qasim') | (names == 'Hassan')]

array([[ 0.21907004, -0.26896777],
       [ 0.57501757,  0.82504974],
       [-0.30574401, -0.763318  ],
       [-0.03896102, -0.03843332]])

In [72]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

print()
data[names=="Qasim"]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-1.2776803   0.50331943  0.98720764 -0.19113135]
 [-0.15860631 -0.28688672  0.95511186 -1.01693884]
 [ 0.44050237 -0.8436115  -1.383417    0.69028585]
 [ 1.73801114  1.04845686  0.85685876  1.24001508]
 [ 0.5005359   1.2165522   0.25375725 -2.23036966]
 [ 1.96785253 -1.62001323  0.91588461  1.62749643]]



array([[-1.2776803 ,  0.50331943,  0.98720764, -0.19113135],
       [ 0.5005359 ,  1.2165522 ,  0.25375725, -2.23036966]])

In [73]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-0.06068375  0.3387716  -1.50581701  2.20496677]
 [ 0.13700314  0.39020035 -0.4729531   0.42857799]
 [ 1.22089511 -0.50412262  0.56435252 -0.75961296]
 [ 0.42900424  0.71007194  0.92358431 -0.29890888]
 [ 0.52012544 -0.0622839  -0.0763662  -0.61146519]
 [-1.276892   -0.89584926  0.0104814  -0.42535948]]


array([[-0.06068375,  0.3387716 , -1.50581701,  2.20496677],
       [ 0.42900424,  0.71007194,  0.92358431, -0.29890888],
       [ 0.52012544, -0.0622839 , -0.0763662 , -0.61146519]])

In [75]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names!="Qasim") &  (names!="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-0.55426503  0.484246    0.91330273  0.65850528]
 [ 1.03436392  1.34927391 -1.20939467 -0.07178511]
 [-0.21684886  1.32351175  1.38295556  3.08716186]
 [ 0.88917974 -1.30477661 -0.22260336  1.01190857]
 [ 0.01180517  1.08889759  0.20047828  0.75532318]
 [-0.69681899  1.23724908 -0.21012891  0.58136249]]


array([[ 1.03436392,  1.34927391, -1.20939467, -0.07178511],
       [-0.21684886,  1.32351175,  1.38295556,  3.08716186],
       [-0.69681899,  1.23724908, -0.21012891,  0.58136249]])

In [76]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")][:,[0,-1]]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-0.80949123  0.22206826 -0.83785716 -2.0726882 ]
 [-0.76660986  1.05926213 -1.13850583  0.68944475]
 [-0.90732457  0.71120459  0.6958054  -0.95087526]
 [ 0.44449058  0.07228728 -0.86210173 -1.26070856]
 [ 0.46689346  0.6713409   0.34313303  1.7640043 ]
 [-0.92796627 -2.20204096  1.22454225  0.4533882 ]]


array([[-0.80949123, -2.0726882 ],
       [ 0.44449058, -1.26070856],
       [ 0.46689346,  1.7640043 ]])

In [77]:
l = [1,3,5,3,5]
l[:3]
l[:3] = 5

TypeError: can only assign an iterable

In [78]:
l = [1,3,5,3,5]
l[:3]
l[0] = 5
l

[5, 3, 5, 3, 5]

In [79]:
l = np.array([1,3,5,3,5]) #eg:image recognition
l[:3]
l[:3] = 5
l

array([5, 5, 5, 3, 5])

In [80]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [82]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [83]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(a.shape[0]):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [84]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


# Transposing Arrays and Swapping Axes

In [1]:
import numpy as np
a = np.arange(4*3).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [2]:
a.T # shallow copy

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [3]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
a.T.T.T.T

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
a.transpose() # shallow copy

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [7]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a * b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[ 3,  8],
       [15, 24]])

In [9]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a @ b # for dot product

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [10]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a.dot(b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [11]:
a.dot(np.ones_like(a).T)

array([[3, 3],
       [7, 7]])

In [12]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.T

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [13]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(2,1,0) # column , row, slide

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [17]:
a = np.arange(3*3).reshape((3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(1,0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [14]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

In [19]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,-2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

# Table 4-3. Unary ufuncs

In [20]:
a = np.array([7,8,-20,2,-3,20])
np.abs(a) # return absolute numbers

array([ 7,  8, 20,  2,  3, 20])

In [21]:
a = np.array([7,8,-20,2,-3,20])
np.fabs(a) # return float absolute numbers

array([ 7.,  8., 20.,  2.,  3., 20.])

In [22]:
a = np.array([36,25,16])
np.fabs(a)

array([36., 25., 16.])

In [23]:
a = np.array([7,8,-20,2,-3,20])
np.square(a) 

array([ 49,  64, 400,   4,   9, 400], dtype=int32)

In [26]:
np.exp??

In [24]:
np.exp(a)

array([1.09663316e+03, 2.98095799e+03, 2.06115362e-09, 7.38905610e+00,
       4.97870684e-02, 4.85165195e+08])

In [27]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.ceil(a)

array([3., 3., 3., 3.])

In [28]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.floor(a)

array([2., 2., 2., 2.])

In [29]:
a = np.array([2.8, 9.7, 5.9])
for i in a:
    i = str(i).split(".")
    print(i[0], i[1])

2 8
9 7
5 9


In [33]:
a = np.array([2.8, 9.7, 5.9])
f, w = np.modf(a)
print(w,f, sep="\n")

[2. 9. 5.]
[0.8 0.7 0.9]


In [40]:
numbers = np.array([1,5,6,np.nan,78])
np.isnan(numbers)

array([False, False, False,  True, False])

In [34]:
np.isnan(np.nan)

True

In [48]:
a = np.array([1,3,5,7])
b = np.array([4,0,2,1])
np.maximum(a,b)

array([4, 3, 5, 7])

In [51]:
a = np.array([1,3,5,7])
b = np.array([4,0,2,1])
c = np.array([8,2,0,1])
np.fmax(a,(b,c))

array([[4, 3, 5, 7],
       [8, 3, 5, 7]])

In [52]:
np.fmax??

# 4.3 Array-Oriented Programming with Arrays

In [53]:
a = np.arange(4*3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

# Expressing Conditional Logic as Array Operations

#### np.where(condition, value_true, value_false)

In [55]:
a = np.arange(8*4).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [56]:
np.where(a%3 == 0, "Yes","No")

array([['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No']], dtype='<U3')

In [57]:
np.where(a%3 == 0, a,0)

array([[ 0,  0,  0,  3],
       [ 0,  0,  6,  0],
       [ 0,  9,  0,  0],
       [12,  0,  0, 15],
       [ 0,  0, 18,  0],
       [ 0, 21,  0,  0],
       [24,  0,  0, 27],
       [ 0,  0, 30,  0]])

In [58]:
[[-1 , 0 , 1],
[-1 , 0 , 1],
[-1 , 0 , 1]]

[[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]]

In [59]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.where(a>b, a, b)

array([3, 3, 5, 7])

# Mathematical and Statistical Methods

In [60]:
a = np.arange(3*4).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
np.sum(a)

66

In [62]:
print(a)
np.sum(a, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [63]:
print(a)
np.sum(a, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

##### Broad Casting

In [64]:
a = np.arange(5*5).reshape((5,5))
print(a)
a + 6

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [65]:
a = np.arange(5*5).reshape((5,5))
b = np.full_like(a, 6)
print(a,b,sep="\n\n")
a + b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## stacking

#### split

# > Stackig

In [66]:
import numpy as np
a = np.random.randint(1,10, size=10)
b = a + 5
print(a, b, sep='\n')
print(len(a),len(b))

[2 8 9 4 1 8 1 1 9 7]
[ 7 13 14  9  6 13  6  6 14 12]
10 10


In [67]:
print(a,b, sep='\n\n')

[2 8 9 4 1 8 1 1 9 7]

[ 7 13 14  9  6 13  6  6 14 12]


In [68]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=0)

[2 8 9 4 1 8 1 1 9 7]

[ 7 13 14  9  6 13  6  6 14 12]


array([[ 2,  8,  9,  4,  1,  8,  1,  1,  9,  7],
       [ 7, 13, 14,  9,  6, 13,  6,  6, 14, 12]])

In [69]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=1)

[2 8 9 4 1 8 1 1 9 7]

[ 7 13 14  9  6 13  6  6 14 12]


array([[ 2,  7],
       [ 8, 13],
       [ 9, 14],
       [ 4,  9],
       [ 1,  6],
       [ 8, 13],
       [ 1,  6],
       [ 1,  6],
       [ 9, 14],
       [ 7, 12]])

In [70]:
# np.stack((a,b), axis=1)
np.column_stack((a,b))

array([[ 2,  7],
       [ 8, 13],
       [ 9, 14],
       [ 4,  9],
       [ 1,  6],
       [ 8, 13],
       [ 1,  6],
       [ 1,  6],
       [ 9, 14],
       [ 7, 12]])

In [71]:
np.stack((a,b), axis=0)

array([[ 2,  8,  9,  4,  1,  8,  1,  1,  9,  7],
       [ 7, 13, 14,  9,  6, 13,  6,  6, 14, 12]])

In [72]:
np.vstack((a,b))

array([[ 2,  8,  9,  4,  1,  8,  1,  1,  9,  7],
       [ 7, 13, 14,  9,  6, 13,  6,  6, 14, 12]])

In [73]:
# 
# 
np.row_stack((a,b))

array([[ 2,  8,  9,  4,  1,  8,  1,  1,  9,  7],
       [ 7, 13, 14,  9,  6, 13,  6,  6, 14, 12]])

In [74]:
np.hstack((a,b))

array([ 2,  8,  9,  4,  1,  8,  1,  1,  9,  7,  7, 13, 14,  9,  6, 13,  6,
        6, 14, 12])

In [75]:
np.vstack((a,b))

array([[ 2,  8,  9,  4,  1,  8,  1,  1,  9,  7],
       [ 7, 13, 14,  9,  6, 13,  6,  6, 14, 12]])

In [78]:
b = np.arange(3*3).reshape((3,3)) 
a = b + 5
print(a, b, sep='\n\n')

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
np.vstack((a,b))

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [80]:
np.hstack((a,b))

array([[ 5,  6,  7,  0,  1,  2],
       [ 8,  9, 10,  3,  4,  5],
       [11, 12, 13,  6,  7,  8]])

In [81]:
np.column_stack((a,b))

array([[ 5,  6,  7,  0,  1,  2],
       [ 8,  9, 10,  3,  4,  5],
       [11, 12, 13,  6,  7,  8]])

In [82]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.dstack((a,b))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[ 0,  1,  7,  8],
        [ 2,  3,  9, 10]],

       [[ 4,  5, 11, 12],
        [ 6,  7, 13, 14]]])

In [92]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.hstack((a,b))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[ 0,  1],
        [ 2,  3],
        [ 7,  8],
        [ 9, 10]],

       [[ 4,  5],
        [ 6,  7],
        [11, 12],
        [13, 14]]])

In [93]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.stack((a,b), axis=2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[[ 0,  1],
         [ 7,  8]],

        [[ 2,  3],
         [ 9, 10]]],


       [[[ 4,  5],
         [11, 12]],

        [[ 6,  7],
         [13, 14]]]])

In [ ]:
np.stack??

In [94]:
a.reshape((2,-1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# Split

In [98]:
a = np.arange(6*6).reshape((6,6))
print(a)
#np.split(a, 6, axis=0)
#np.split(a, 3, axis=0)
#np.split(a, 2, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [103]:
a = np.arange(6*6).reshape((6,6))
print(a)
#np.split(a, 6, axis=1)
np.split(a, 3, axis=1)
#np.split(a, 2, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [104]:
a = np.arange(2*2*2).reshape((2,2,2))
p=print(a)

np.dsplit(a, 2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

# Table 4-6. Array set operations

In [105]:
a = np.random.randint(1,10, size=20)
print(a)
np.unique(a)

[3 8 4 1 6 8 7 5 9 3 6 5 9 7 8 7 1 7 7 1]


array([1, 3, 4, 5, 6, 7, 8, 9])

In [108]:
piaic = np.random.randint(1,100, size=30)
cnic = np.random.randint(1,10, size=5)
print(piaic, cnic,sep='\n\n')

[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]


In [109]:
[True if x in piaic else False for x in cnic]

[False, False, True, False, False]

In [ ]:
[true_block if condition else false_block for x in data]

In [110]:
[x in piaic for x in cnic]

[False, False, True, False, False]

In [111]:
["Yes" if x in piaic else "NO" for x in cnic]

['NO', 'NO', 'Yes', 'NO', 'NO']

In [112]:
print(piaic, cnic,sep='\n\n')
np.in1d(cnic, piaic)


[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]


array([False, False,  True, False, False])

In [114]:
print(piaic, cnic,sep='\n\n')
c = np.in1d(cnic, piaic)
print(c)
np.where(c==True,"Yes","No")

[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]
[False False  True False False]


array(['No', 'No', 'Yes', 'No', 'No'], dtype='<U3')

In [117]:
print(piaic, cnic,sep='\n\n')
c = np.in1d(cnic, piaic)
print(c)
cnic[c]

[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]
[False False  True False False]


array([6])

In [115]:
print(piaic, cnic,sep='\n\n')
np.intersect1d(cnic, piaic)

[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]


array([6])

In [118]:
print(piaic, cnic,sep='\n\n')
np.union1d(cnic, piaic)

[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]


array([ 5,  6,  8, 10, 11, 23, 29, 30, 37, 39, 41, 43, 45, 48, 57, 58, 60,
       62, 65, 66, 72, 75, 77, 79, 81, 84, 88, 92])

In [119]:
print(piaic, cnic,sep='\n\n')
np.setdiff1d(cnic, piaic)

[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]


array([5, 8])

In [120]:
# XOR
# 0 0 -> 0
# 1 0 -> 1
# 0 1 -> 1
# 1 1 -> 0
print(piaic, cnic,sep='\n\n')
np.setxor1d(cnic, piaic)

[11 60 79 92 66  6 45 30 10 77 57 29 39 37 39 65 48 48 75 84 81 62 75 88
 41 58 72 43 88 23]

[8 5 6 5 8]


array([ 5,  8, 10, 11, 23, 29, 30, 37, 39, 41, 43, 45, 48, 57, 58, 60, 62,
       65, 66, 72, 75, 77, 79, 81, 84, 88, 92])